# proto-file: configuration/config.proto
# proto-message: Config

environment {
  num_agents: 16
  agario {
    difficulty: EMPTY
    num_pellets: 1000
    arena_size: 1000
    num_viruses: 0
    num_bots: 0
  }
  observation {
    type: GRID
    ticks_per_step: 4
    grid_size: 64
    viruses: false
  }
  action {
    num_directions: 8
    num_magnitudes: 1
  }
}
model {
  feature_extractor {
    num_features: 1024
  }
}
hyperparameters {
  num_episodes: 10000
  episode_length: 512

  num_sgd_steps: 8
  batch_size: 128

  feature_extractor_lr {
    shift: 0.00001
    exponential_decay {
      base: 0.001
      decay_steps: 500
      decay_rate: 2.718281828459
    }
  }
  actor_lr {
    shift: 0.00001
    exponential_decay {
      base: 0.001
      decay_steps: 500
      decay_rate: 2.7182818284590
    }
  }
  critic_lr {
    scale: 10.0
    shift: 0.0001
    exponential_decay {
      base: 0.001
      decay_steps: 500
      decay_rate: 2.7182818284590
    }
  }

  gamma: 0.75  # Did extensive sweep.

  # Generalized Advantage Estimation.
  # 0 -> TD (low variance)
  # 1 -> Monte-Carlo (high variance)
  gae { lam: 0.1 }
  loss {
    # Proximal policy optimization.
    ppo { clip_epsilon: REPLACE }
  }
}