# proto-file: configuration/config.proto
# proto-message: Config

environment {
  num_agents: 16
  agario {
    difficulty: EMPTY
    num_pellets: 1000
    arena_size: 1000
    num_viruses: 0
    num_bots: 0
  }
  observation {
    type: GRID
    ticks_per_step: 2
  }
  action {
    num_directions: 8
    num_magnitudes: 1
  }
}
model {
  feature_extractor {
    num_features: 1024
  }
}
hyperparameters {
  num_episodes: 10000
  episode_length: 2048

  num_sgd_steps: 40
#  batch_size: 256

  learning_rate: 0.05
  gamma: 0.7
}