# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import environment_pb2 as environment__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='config.proto',
  package='configuration',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63onfig.proto\x12\rconfiguration\x1a\x11\x65nvironment.proto\"\xdd\x02\n\x0fHyperParameters\x12\x0f\n\x04seed\x18\x01 \x01(\x03:\x01\x30\x12\x15\n\rlearning_rate\x18\x02 \x01(\x02\x12\x14\n\x0cnum_episodes\x18\x03 \x01(\x03\x12\x16\n\x0e\x65pisode_length\x18\t \x01(\x03\x12\r\n\x05gamma\x18\x04 \x01(\x02\x12/\n\x03gae\x18\n \x01(\x0b\x32\".configuration.HyperParameters.GAE\x12/\n\x03ppo\x18\x0b \x01(\x0b\x32\".configuration.HyperParameters.PPO\x12\r\n\x05\x62\x61tch\x18\x05 \x01(\x08\x12\x12\n\nbatch_size\x18\x06 \x01(\x03\x12\x15\n\rnum_sgd_steps\x18\x08 \x01(\x03\x12\x18\n\x10num_environments\x18\x07 \x01(\x03\x1a\x12\n\x03GAE\x12\x0b\n\x03lam\x18\x01 \x01(\x02\x1a\x1b\n\x03PPO\x12\x14\n\x0c\x63lip_epsilon\x18\x01 \x01(\x02\"s\n\x05Model\x12@\n\x11\x66\x65\x61ture_extractor\x18\x01 \x01(\x0b\x32%.configuration.Model.FeatureExtractor\x1a(\n\x10\x46\x65\x61tureExtractor\x12\x14\n\x0cnum_features\x18\x02 \x01(\x03\"\xa3\x02\n\x06\x43onfig\x12/\n\x0b\x65nvironment\x18\x01 \x01(\x0b\x32\x1a.configuration.Environment\x12\x34\n\x10test_environment\x18\x02 \x01(\x0b\x32\x1a.configuration.Environment\x12\x37\n\x0fhyperparameters\x18\x03 \x01(\x0b\x32\x1e.configuration.HyperParameters\x12#\n\x05model\x18\x04 \x01(\x0b\x32\x14.configuration.Model\x12\x30\n\x08training\x18\x05 \x01(\x0b\x32\x1e.configuration.Config.Training\x1a\"\n\x08Training\x12\x16\n\x0esave_frequency\x18\x01 \x01(\x03'
  ,
  dependencies=[environment__pb2.DESCRIPTOR,])




_HYPERPARAMETERS_GAE = _descriptor.Descriptor(
  name='GAE',
  full_name='configuration.HyperParameters.GAE',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lam', full_name='configuration.HyperParameters.GAE.lam', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=371,
)

_HYPERPARAMETERS_PPO = _descriptor.Descriptor(
  name='PPO',
  full_name='configuration.HyperParameters.PPO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='clip_epsilon', full_name='configuration.HyperParameters.PPO.clip_epsilon', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=400,
)

_HYPERPARAMETERS = _descriptor.Descriptor(
  name='HyperParameters',
  full_name='configuration.HyperParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seed', full_name='configuration.HyperParameters.seed', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='learning_rate', full_name='configuration.HyperParameters.learning_rate', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_episodes', full_name='configuration.HyperParameters.num_episodes', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='episode_length', full_name='configuration.HyperParameters.episode_length', index=3,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gamma', full_name='configuration.HyperParameters.gamma', index=4,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gae', full_name='configuration.HyperParameters.gae', index=5,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ppo', full_name='configuration.HyperParameters.ppo', index=6,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch', full_name='configuration.HyperParameters.batch', index=7,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='configuration.HyperParameters.batch_size', index=8,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_sgd_steps', full_name='configuration.HyperParameters.num_sgd_steps', index=9,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_environments', full_name='configuration.HyperParameters.num_environments', index=10,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_HYPERPARAMETERS_GAE, _HYPERPARAMETERS_PPO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=400,
)


_MODEL_FEATUREEXTRACTOR = _descriptor.Descriptor(
  name='FeatureExtractor',
  full_name='configuration.Model.FeatureExtractor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_features', full_name='configuration.Model.FeatureExtractor.num_features', index=0,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=477,
  serialized_end=517,
)

_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='configuration.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature_extractor', full_name='configuration.Model.feature_extractor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MODEL_FEATUREEXTRACTOR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=402,
  serialized_end=517,
)


_CONFIG_TRAINING = _descriptor.Descriptor(
  name='Training',
  full_name='configuration.Config.Training',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='save_frequency', full_name='configuration.Config.Training.save_frequency', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=777,
  serialized_end=811,
)

_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='configuration.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='environment', full_name='configuration.Config.environment', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='test_environment', full_name='configuration.Config.test_environment', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hyperparameters', full_name='configuration.Config.hyperparameters', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='configuration.Config.model', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='training', full_name='configuration.Config.training', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CONFIG_TRAINING, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=811,
)

_HYPERPARAMETERS_GAE.containing_type = _HYPERPARAMETERS
_HYPERPARAMETERS_PPO.containing_type = _HYPERPARAMETERS
_HYPERPARAMETERS.fields_by_name['gae'].message_type = _HYPERPARAMETERS_GAE
_HYPERPARAMETERS.fields_by_name['ppo'].message_type = _HYPERPARAMETERS_PPO
_MODEL_FEATUREEXTRACTOR.containing_type = _MODEL
_MODEL.fields_by_name['feature_extractor'].message_type = _MODEL_FEATUREEXTRACTOR
_CONFIG_TRAINING.containing_type = _CONFIG
_CONFIG.fields_by_name['environment'].message_type = environment__pb2._ENVIRONMENT
_CONFIG.fields_by_name['test_environment'].message_type = environment__pb2._ENVIRONMENT
_CONFIG.fields_by_name['hyperparameters'].message_type = _HYPERPARAMETERS
_CONFIG.fields_by_name['model'].message_type = _MODEL
_CONFIG.fields_by_name['training'].message_type = _CONFIG_TRAINING
DESCRIPTOR.message_types_by_name['HyperParameters'] = _HYPERPARAMETERS
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HyperParameters = _reflection.GeneratedProtocolMessageType('HyperParameters', (_message.Message,), {

  'GAE' : _reflection.GeneratedProtocolMessageType('GAE', (_message.Message,), {
    'DESCRIPTOR' : _HYPERPARAMETERS_GAE,
    '__module__' : 'config_pb2'
    # @@protoc_insertion_point(class_scope:configuration.HyperParameters.GAE)
    })
  ,

  'PPO' : _reflection.GeneratedProtocolMessageType('PPO', (_message.Message,), {
    'DESCRIPTOR' : _HYPERPARAMETERS_PPO,
    '__module__' : 'config_pb2'
    # @@protoc_insertion_point(class_scope:configuration.HyperParameters.PPO)
    })
  ,
  'DESCRIPTOR' : _HYPERPARAMETERS,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:configuration.HyperParameters)
  })
_sym_db.RegisterMessage(HyperParameters)
_sym_db.RegisterMessage(HyperParameters.GAE)
_sym_db.RegisterMessage(HyperParameters.PPO)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), {

  'FeatureExtractor' : _reflection.GeneratedProtocolMessageType('FeatureExtractor', (_message.Message,), {
    'DESCRIPTOR' : _MODEL_FEATUREEXTRACTOR,
    '__module__' : 'config_pb2'
    # @@protoc_insertion_point(class_scope:configuration.Model.FeatureExtractor)
    })
  ,
  'DESCRIPTOR' : _MODEL,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:configuration.Model)
  })
_sym_db.RegisterMessage(Model)
_sym_db.RegisterMessage(Model.FeatureExtractor)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {

  'Training' : _reflection.GeneratedProtocolMessageType('Training', (_message.Message,), {
    'DESCRIPTOR' : _CONFIG_TRAINING,
    '__module__' : 'config_pb2'
    # @@protoc_insertion_point(class_scope:configuration.Config.Training)
    })
  ,
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'config_pb2'
  # @@protoc_insertion_point(class_scope:configuration.Config)
  })
_sym_db.RegisterMessage(Config)
_sym_db.RegisterMessage(Config.Training)


# @@protoc_insertion_point(module_scope)
