# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: environment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='environment.proto',
  package='configuration',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x65nvironment.proto\x12\rconfiguration\"\xe3\x01\n\x06\x41gario\x12\x34\n\ndifficulty\x18\x01 \x01(\x0e\x32 .configuration.Agario.Difficulty\x12\x12\n\narena_size\x18\x07 \x01(\x03\x12\x13\n\x0bnum_pellets\x18\x03 \x01(\x03\x12\x13\n\x0bnum_viruses\x18\x04 \x01(\x03\x12\x10\n\x08num_bots\x18\x05 \x01(\x03\x12\x14\n\x0cpellet_regen\x18\x06 \x01(\x08\"=\n\nDifficulty\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07TRIVIAL\x10\x01\x12\t\n\x05\x45MPTY\x10\x02\x12\n\n\x06NORMAL\x10\x03\"v\n\x06\x41\x63tion\x12\x16\n\x0enum_directions\x18\x01 \x01(\x03\x12\x16\n\x0enum_magnitudes\x18\x02 \x01(\x03\x12\x1e\n\x0f\x61llow_splitting\x18\x03 \x01(\x08:\x05\x66\x61lse\x12\x1c\n\rallow_feeding\x18\x04 \x01(\x08:\x05\x66\x61lse\"\x92\x02\n\x0bObservation\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x1f.configuration.Observation.Type\x12\x15\n\nnum_frames\x18\x02 \x01(\x03:\x01\x31\x12\x19\n\x0eticks_per_step\x18\x08 \x01(\x03:\x01\x34\x12\x15\n\tgrid_size\x18\x03 \x01(\x03:\x02\x36\x34\x12\x15\n\x07pellets\x18\x04 \x01(\x08:\x04true\x12\x15\n\x07viruses\x18\x05 \x01(\x08:\x04true\x12\x13\n\x05\x63\x65lls\x18\x06 \x01(\x08:\x04true\x12\x14\n\x06others\x18\x07 \x01(\x08:\x04true\"2\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04GRID\x10\x01\x12\x07\n\x03RAM\x10\x02\x12\n\n\x06SCREEN\x10\x03\"\xa3\x01\n\x0b\x45nvironment\x12%\n\x06\x61gario\x18\x01 \x01(\x0b\x32\x15.configuration.Agario\x12\x15\n\nnum_agents\x18\x02 \x01(\x03:\x01\x31\x12/\n\x0bobservation\x18\x03 \x01(\x0b\x32\x1a.configuration.Observation\x12%\n\x06\x61\x63tion\x18\x05 \x01(\x0b\x32\x15.configuration.Action'
)



_AGARIO_DIFFICULTY = _descriptor.EnumDescriptor(
  name='Difficulty',
  full_name='configuration.Agario.Difficulty',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRIVIAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EMPTY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NORMAL', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=203,
  serialized_end=264,
)
_sym_db.RegisterEnumDescriptor(_AGARIO_DIFFICULTY)

_OBSERVATION_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='configuration.Observation.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GRID', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RAM', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SCREEN', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=611,
  serialized_end=661,
)
_sym_db.RegisterEnumDescriptor(_OBSERVATION_TYPE)


_AGARIO = _descriptor.Descriptor(
  name='Agario',
  full_name='configuration.Agario',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='difficulty', full_name='configuration.Agario.difficulty', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arena_size', full_name='configuration.Agario.arena_size', index=1,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_pellets', full_name='configuration.Agario.num_pellets', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_viruses', full_name='configuration.Agario.num_viruses', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_bots', full_name='configuration.Agario.num_bots', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pellet_regen', full_name='configuration.Agario.pellet_regen', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AGARIO_DIFFICULTY,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=264,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='configuration.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_directions', full_name='configuration.Action.num_directions', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_magnitudes', full_name='configuration.Action.num_magnitudes', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allow_splitting', full_name='configuration.Action.allow_splitting', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allow_feeding', full_name='configuration.Action.allow_feeding', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=384,
)


_OBSERVATION = _descriptor.Descriptor(
  name='Observation',
  full_name='configuration.Observation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='configuration.Observation.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_frames', full_name='configuration.Observation.num_frames', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ticks_per_step', full_name='configuration.Observation.ticks_per_step', index=2,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='grid_size', full_name='configuration.Observation.grid_size', index=3,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=64,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pellets', full_name='configuration.Observation.pellets', index=4,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='viruses', full_name='configuration.Observation.viruses', index=5,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cells', full_name='configuration.Observation.cells', index=6,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='others', full_name='configuration.Observation.others', index=7,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OBSERVATION_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=661,
)


_ENVIRONMENT = _descriptor.Descriptor(
  name='Environment',
  full_name='configuration.Environment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='agario', full_name='configuration.Environment.agario', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_agents', full_name='configuration.Environment.num_agents', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='observation', full_name='configuration.Environment.observation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='action', full_name='configuration.Environment.action', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=664,
  serialized_end=827,
)

_AGARIO.fields_by_name['difficulty'].enum_type = _AGARIO_DIFFICULTY
_AGARIO_DIFFICULTY.containing_type = _AGARIO
_OBSERVATION.fields_by_name['type'].enum_type = _OBSERVATION_TYPE
_OBSERVATION_TYPE.containing_type = _OBSERVATION
_ENVIRONMENT.fields_by_name['agario'].message_type = _AGARIO
_ENVIRONMENT.fields_by_name['observation'].message_type = _OBSERVATION
_ENVIRONMENT.fields_by_name['action'].message_type = _ACTION
DESCRIPTOR.message_types_by_name['Agario'] = _AGARIO
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.message_types_by_name['Observation'] = _OBSERVATION
DESCRIPTOR.message_types_by_name['Environment'] = _ENVIRONMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Agario = _reflection.GeneratedProtocolMessageType('Agario', (_message.Message,), {
  'DESCRIPTOR' : _AGARIO,
  '__module__' : 'environment_pb2'
  # @@protoc_insertion_point(class_scope:configuration.Agario)
  })
_sym_db.RegisterMessage(Agario)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'environment_pb2'
  # @@protoc_insertion_point(class_scope:configuration.Action)
  })
_sym_db.RegisterMessage(Action)

Observation = _reflection.GeneratedProtocolMessageType('Observation', (_message.Message,), {
  'DESCRIPTOR' : _OBSERVATION,
  '__module__' : 'environment_pb2'
  # @@protoc_insertion_point(class_scope:configuration.Observation)
  })
_sym_db.RegisterMessage(Observation)

Environment = _reflection.GeneratedProtocolMessageType('Environment', (_message.Message,), {
  'DESCRIPTOR' : _ENVIRONMENT,
  '__module__' : 'environment_pb2'
  # @@protoc_insertion_point(class_scope:configuration.Environment)
  })
_sym_db.RegisterMessage(Environment)


# @@protoc_insertion_point(module_scope)
